#Server Settings
server:
  port: 8081

spring:
  ## Datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/guestdb
    username: guestuser
    password: guestpassword
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # Application Name
  application:
    name: guest-service

#Eureka Service Discovery Settings
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
